### ISSUE TITLE
Questions about targets of LBA in atom3d paper

### ISSUE THREAD

**Issue by Wufang1997** [drorlab/atom3d#31]
Hi, as clarified in the atom3D paper, the metrics for the LBD dataset is ‘-log(K)‘. Do we need to further calculate the log negative score by ourselves, or the value of `item['scores']['neglog_aff']` is already preprocessed? 

Besides, I notice there are two types of proteins: one is the original one and the other is the pocket. Can I use pocket-ligand pair to predict the binding affinity? Since the pocket contains far less atoms.

**Comment by Wufang1997** [comment]
One more question (too many questions hhh), what is the meaning of global R_p and R_s? Does the term global correspond to both the training and testing samples?

**Comment by martinvoegele** [comment]
Hi, thanks for your questions! 

1. The value of `item['scores']['neglog_aff']` is already ‘-log(K)‘.
2. You can use the pocket-ligand pair. It is not a priori clear how much of the protein would have to be used so someone might want to use a different definition for the pocket (or even use the entire protein). That's why we included this, too.
3. R_p and R_s are Pearson and Spearman correlation coefficients. They are calculated calculated for the **test** set only. The term "global" has in fact no particular meaning for LBA because there, each molecule only has one target data point. We use "global" for the PSR and RSR datasets to distinguish the correlation calculated for all data points jointly from the mean of the correlations calculated for each target separately.
