### ISSUE TITLE
Providing data access in standard formats

### ISSUE THREAD

**Issue by rmwu** [drorlab/atom3d#36]
Hello! I was wondering whether you would consider providing your datasets in standard formats for ease of integration into existing frameworks, outside of your API + LMDB files. In particular, I'm looking to evaluate on the LEP dataset with code that operates on PDBbind-like structures (i.e. raw PDB file for protein, mol2/sdf for ligand). Let me know, and thank you!

**Comment by martinvoegele** [comment]
Hi, thanks for your interest in our datasets! 

As it is difficult to maintain datasets in various different formats, we have decided to use only one and picked LMDB because it is (a) efficient to read and distribute and (b) flexible and extendable.

I think there are two options:
1) You are maintaining the code you mention yourself.
Then it is probably easiest to import the LMDB reader from ATOM3D.
2) You are using another code out of the box.
Then you can convert the LMDB dataset to PDB, SDF, etc. Unfortunately, there is no function in ATOM3D that does that yet and we are currently quite busy so it might take a while until one of us gets to implement it. If you would like to go ahead and implement the necessary functionality, you can draw inspiration from the following functions:
`make_lmdb_dataset()`
https://github.com/drorlab/atom3d/blob/d8ee23444a5a209d6247ffb08c17c8b03b30cd68/atom3d/datasets/datasets.py#L443
`extract_coordinates_as_numpy_arrays()`
https://github.com/drorlab/atom3d/blob/d8ee23444a5a209d6247ffb08c17c8b03b30cd68/atom3d/datasets/datasets.py#L494
Please let us know if you do so because we would be happy to include this functionality.

**Comment by martinvoegele** [comment]
I have added a function `write_lmdb_as_pdb(lmdb_dir, output_dir)` to `atom3d.datasets.datasets` that converts an LMDB dataset to a set of PDB files: 
https://github.com/drorlab/atom3d/blob/463c2ca3fd11cd56d587e281bdc14c6658903a34/atom3d/datasets/datasets.py#L496
