### ISSUE TITLE
Benchmark for Atom3D

### ISSUE THREAD

**Issue by guochengqian** [drorlab/atom3d#49]
Hi @drorlab, 

Thank you for contributing Atom3D. I would like to know where can we know the benchmark information for those datasets? Are you going to maintain a benchmark just like OGB? 
thank you!

**Comment by smiles724** [comment]
I think it might be unreasonable for the ATOM3D to maintain the benchmark information. Since there are many different kinds of tasks, each one corresponds to different areas. For instance, QM9 focuses on the quantum mechanics of small molecules, where tremendous methods have been invented to solve this problem. The state-of-the-art records are changing constantly. I believe it is the researchers' responsibility to collect this information.

**Comment by guochengqian** [comment]
okay. Understanable. Thanks for the reply.
